package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 17 09:59:45 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for CustVehicleReqHeaderVO1.
     * @return CustVehicleReqHeaderVO1
     */
    public ViewObjectImpl getCustVehicleReqHeaderVO1() {
        return (ViewObjectImpl) findViewObject("CustVehicleReqHeaderVO1");
    }

    /**
     * Container's getter for DepatmentVO1.
     * @return DepatmentVO1
     */
    public DepatmentVOImpl getDepatmentVO1() {
        return (DepatmentVOImpl) findViewObject("DepatmentVO1");
    }

    /**
     * Container's getter for VehicleTypeVO1.
     * @return VehicleTypeVO1
     */
    public VehicleTypeVOImpl getVehicleTypeVO1() {
        return (VehicleTypeVOImpl) findViewObject("VehicleTypeVO1");
    }
 
}

