package model;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 04 14:39:10 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustVehicleReqHeaderVORowImpl extends ViewRowImpl implements model.common.CustVehicleReqHeaderVORow {


    public static final int ENTITY_CUSTVEHICLEREQHEADEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        VrReqId,
        VrRequisitionNumber,
        DepId,
        VrDemandDate,
        VrRequiredDate,
        VehicleTypeId,
        Purpose,
        ApproxDuration,
        ApproxDistance,
        Status,
        VrOrgId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        VersionNumber,
        UserId,
        AppModule_DepatmentVO1_1,
        AppModule_VehicleTypeVO1_1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VRREQID = AttributesEnum.VrReqId.index();
    public static final int VRREQUISITIONNUMBER = AttributesEnum.VrRequisitionNumber.index();
    public static final int DEPID = AttributesEnum.DepId.index();
    public static final int VRDEMANDDATE = AttributesEnum.VrDemandDate.index();
    public static final int VRREQUIREDDATE = AttributesEnum.VrRequiredDate.index();
    public static final int VEHICLETYPEID = AttributesEnum.VehicleTypeId.index();
    public static final int PURPOSE = AttributesEnum.Purpose.index();
    public static final int APPROXDURATION = AttributesEnum.ApproxDuration.index();
    public static final int APPROXDISTANCE = AttributesEnum.ApproxDistance.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VRORGID = AttributesEnum.VrOrgId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int APPMODULE_DEPATMENTVO1_1 = AttributesEnum.AppModule_DepatmentVO1_1.index();
    public static final int APPMODULE_VEHICLETYPEVO1_1 = AttributesEnum.AppModule_VehicleTypeVO1_1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustVehicleReqHeaderVORowImpl() {
    }

    /**
     * Gets CustVehicleReqHeaderEO entity object.
     * @return the CustVehicleReqHeaderEO
     */
    public CustVehicleReqHeaderEOImpl getCustVehicleReqHeaderEO() {
        return (CustVehicleReqHeaderEOImpl) getEntity(ENTITY_CUSTVEHICLEREQHEADEREO);
    }

    /**
     * Gets the attribute value for VR_REQ_ID using the alias name VrReqId.
     * @return the VR_REQ_ID
     */
    public BigDecimal getVrReqId() {
        return (BigDecimal) getAttributeInternal(VRREQID);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_REQ_ID using the alias name VrReqId.
     * @param value value to set the VR_REQ_ID
     */
    public void setVrReqId(BigDecimal value) {
        setAttributeInternal(VRREQID, value);
    }

    /**
     * Gets the attribute value for VR_REQUISITION_NUMBER using the alias name VrRequisitionNumber.
     * @return the VR_REQUISITION_NUMBER
     */
    public BigDecimal getVrRequisitionNumber() {
        return (BigDecimal) getAttributeInternal(VRREQUISITIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_REQUISITION_NUMBER using the alias name VrRequisitionNumber.
     * @param value value to set the VR_REQUISITION_NUMBER
     */
    public void setVrRequisitionNumber(BigDecimal value) {
        setAttributeInternal(VRREQUISITIONNUMBER, value);
    }

    /**
     * Gets the attribute value for DEP_ID using the alias name DepId.
     * @return the DEP_ID
     */
    public String getDepId() {
        return (String) getAttributeInternal(DEPID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEP_ID using the alias name DepId.
     * @param value value to set the DEP_ID
     */
    public void setDepId(String value) {
        setAttributeInternal(DEPID, value);
    }

    /**
     * Gets the attribute value for VR_DEMAND_DATE using the alias name VrDemandDate.
     * @return the VR_DEMAND_DATE
     */
    public Timestamp getVrDemandDate() {
        return (Timestamp) getAttributeInternal(VRDEMANDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_DEMAND_DATE using the alias name VrDemandDate.
     * @param value value to set the VR_DEMAND_DATE
     */
    public void setVrDemandDate(Timestamp value) {
        setAttributeInternal(VRDEMANDDATE, value);
    }

    /**
     * Gets the attribute value for VR_REQUIRED_DATE using the alias name VrRequiredDate.
     * @return the VR_REQUIRED_DATE
     */
    public Timestamp getVrRequiredDate() {
        return (Timestamp) getAttributeInternal(VRREQUIREDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_REQUIRED_DATE using the alias name VrRequiredDate.
     * @param value value to set the VR_REQUIRED_DATE
     */
    public void setVrRequiredDate(Timestamp value) {
        setAttributeInternal(VRREQUIREDDATE, value);
    }

    /**
     * Gets the attribute value for VEHICLE_TYPE_ID using the alias name VehicleTypeId.
     * @return the VEHICLE_TYPE_ID
     */
    public BigDecimal getVehicleTypeId() {
        return (BigDecimal) getAttributeInternal(VEHICLETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_TYPE_ID using the alias name VehicleTypeId.
     * @param value value to set the VEHICLE_TYPE_ID
     */
    public void setVehicleTypeId(BigDecimal value) {
        setAttributeInternal(VEHICLETYPEID, value);
    }

    /**
     * Gets the attribute value for PURPOSE using the alias name Purpose.
     * @return the PURPOSE
     */
    public String getPurpose() {
        return (String) getAttributeInternal(PURPOSE);
    }

    /**
     * Sets <code>value</code> as attribute value for PURPOSE using the alias name Purpose.
     * @param value value to set the PURPOSE
     */
    public void setPurpose(String value) {
        setAttributeInternal(PURPOSE, value);
    }

    /**
     * Gets the attribute value for APPROX_DURATION using the alias name ApproxDuration.
     * @return the APPROX_DURATION
     */
    public String getApproxDuration() {
        return (String) getAttributeInternal(APPROXDURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROX_DURATION using the alias name ApproxDuration.
     * @param value value to set the APPROX_DURATION
     */
    public void setApproxDuration(String value) {
        setAttributeInternal(APPROXDURATION, value);
    }

    /**
     * Gets the attribute value for APPROX_DISTANCE using the alias name ApproxDistance.
     * @return the APPROX_DISTANCE
     */
    public BigDecimal getApproxDistance() {
        return (BigDecimal) getAttributeInternal(APPROXDISTANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROX_DISTANCE using the alias name ApproxDistance.
     * @param value value to set the APPROX_DISTANCE
     */
    public void setApproxDistance(BigDecimal value) {
        setAttributeInternal(APPROXDISTANCE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for VR_ORG_ID using the alias name VrOrgId.
     * @return the VR_ORG_ID
     */
    public BigDecimal getVrOrgId() {
        return (BigDecimal) getAttributeInternal(VRORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_ORG_ID using the alias name VrOrgId.
     * @param value value to set the VR_ORG_ID
     */
    public void setVrOrgId(BigDecimal value) {
        setAttributeInternal(VRORGID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_DepatmentVO1_1.
     */
    public RowSet getAppModule_DepatmentVO1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_DEPATMENTVO1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_VehicleTypeVO1_1.
     */
    public RowSet getAppModule_VehicleTypeVO1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_VEHICLETYPEVO1_1);
    }
    public void initiateWorkflow(int reqID){
        CallableStatement cst = null;
        try{
            cst = getDBTransaction().createCallableStatement("{call APPS.vrf_engine.execWF(?)}", 0);
            cst.setInt(1, reqID);   
            cst.executeUpdate();
            getDBTransaction().commit();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
}

