package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 13 16:28:41 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VehicleTypeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VehicleTypeVOImpl() {
    }
}

