package model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 08 12:11:08 PKT 2018
// ---------------------------------------------------------------------
public interface ApprovedRequisitionsRow extends Row {
    void finalizeTravel();
}

