package model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 04 14:41:48 PKT 2018
// ---------------------------------------------------------------------
public interface CustVehicleReqHeaderVORow extends Row {
    void initiateWorkflow(int reqID);
}

